version: '3.8'
services:
  webapi:
    build:
      context: ./RentManagerAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: breno123
      POSTGRES_DB: RentManagerDB
    ports:
      - "5432:5432"
